export const ACADEMIC_PERIODS = [
  { id: 'pre-test', label: 'តេស្តដើមឆ្នាំ' },
  { id: 'nov', label: 'ខែវិច្ឆិកា (November - ទទេ)' },
  { id: 'dec', label: 'ខែធ្នូ' },
  { id: 'jan', label: 'ខែមករា' },
  { id: 'feb', label: 'ខែកុម្ភៈ' },
  { id: 'sem1-exam', label: 'ប្រលងឆមាសលើកទី១' },
  { id: 'sem1-summary', label: 'ប្រចាំឆមាសលើកទី១' },
  { id: 'mar', label: 'ខែមីនា' },
  { id: 'apr', label: 'ខែមេសា (April - ទទេ)' },
  { id: 'may', label: 'ខែឧសភា' },
  { id: 'jun', label: 'ខែមិថុនា' },
  { id: 'jul', label: 'ខែកក្កដា' },
  { id: 'sem2-exam', label: 'ប្រលងឆមាសលើកទី២' },
  { id: 'sem2-summary', label: 'ប្រចាំឆមាសលើកទី២' },
  { id: 'annual', label: 'លទ្ធផលដំណាច់ឆ្នាំ' },
];
