export const ACADEMIC_PERIODS = [
  { id: 'pre-test', label: 'តេស្តដើមឆ្នាំ (Pre-test)' },
  { id: 'nov', label: 'ខែវិច្ឆិកា (November - ទទេ)' },
  { id: 'dec', label: 'ខែធ្នូ (December)' },
  { id: 'jan', label: 'ខែមករា (January)' },
  { id: 'feb', label: 'ខែកុម្ភៈ (February)' },
  { id: 'sem1-exam', label: 'ប្រលងឆមាសលើកទី១ (Semester 1 Exam)' },
  { id: 'sem1-summary', label: 'ប្រចាំឆមាសលើកទី១ (Semester 1 Summary)' },
  { id: 'mar', label: 'ខែមីនា (March)' },
  { id: 'apr', label: 'ខែមេសា (April - ទទេ)' },
  { id: 'may', label: 'ខែឧសភា (May)' },
  { id: 'jun', label: 'ខែមិថុនា (June)' },
  { id: 'jul', label: 'ខែកក្កដា (July)' },
  { id: 'sem2-exam', label: 'ប្រលងឆមាសលើកទី២ (Semester 2 Exam)' },
  { id: 'sem2-summary', label: 'ប្រចាំឆមាសលើកទី២ (Semester 2 Summary)' },
  { id: 'annual', label: 'លទ្ធផលដំណាច់ឆ្នាំ (Annual Result)' },
];
